global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0

  plugins:
    - { name: static_map, type: "costmap_2d::StaticLayer" }
    - { name: inflation_layer,   type: "costmap_2d::InflationLayer" }
