local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05

  plugins:
    - { name: obstacle_layer,        type: "costmap_2d::VoxelLayer" }
    - { name: inflation_layer, type: 'costmap_2d::InflationLayer' }


  inflation_layer: {cost_scaling_factor: 10.0, enabled: true, inflation_radius: 0.22, robot_radius: 0.22}

  obstacle_layer:
    observation_sources: scan
    scan: { clearing: true, data_type: LaserScan, marking: true, max_obstacle_height: 1.0, inf_is_valid: true,
            min_obstacle_height: 0.05, topic: /scan }
    track_unknown_space: false